
all:
	# nsmake run -g3 tests/benchmarks/bench_ConvexPolyhedron2.cpp
	# nsmake run -g3 tests/test_ConvexPolyhedron2.cpp
	nsmake run -g3 tests/benchmarks/bench_Zgrid.cpp
	# nsmake run -I/usr/local/include/geogram1 -g3 tests/benchmarks/bench_geogram_delaunay.cpp
 
