RUN = nsmake run -g3 # --exec-with "valgrind --num-callers=64"

all:
	# nsmake run -g3 tests/benchmarks/bench_ConvexPolyhedron2.cpp
	nsmake run -g3 tests/benchmarks/bench_ConvexPolyhedron3.cpp
	# nsmake run -g3 tests/benchmarks/bench_ConvexPolyhedron3b.cpp
	# nsmake run -g3 tests/test_ConvexPolyhedron2.cpp
	# ${RUN} tests/benchmarks/bench_Zgrid_2D.cpp
	# ${RUN} tests/benchmarks/bench_Zgrid_2D.cpp
	# nsmake run tests/benchmarks/bench_CGAL.cpp
	# nsmake run tests/benchmarks/bench_CGAL_3D.cpp
	# nsmake run -g3 tests/test_RadixSort.cpp
	# ${RUN} -I/usr/local/include/geogram1 -g3 tests/benchmarks/bench_geogram_delaunay_2D.cpp
	# ${RUN} -I/usr/local/include/geogram1 -g3 tests/benchmarks/bench_geogram_3D.cpp
	# nsmake run -g3 tests/benchmarks/make_distrib_voro.cpp
	# nsmake run -g3 tests/test_IntrusivePool.cpp
	# nsmake run -g3 tests/test_PointerWithOffset.cpp
	# nsmake run -g3 tests/test_ConvexPolyhedron3.cpp
	# ${RUN} tests/Grids/test_LGrid_2D.cpp
	# nsmake run -g3 --exec-with valgrind tests/test_solve_2D.cpp
	nsmake run -g3 tests/benchmarks/bench_Lgrid.cpp
	# ${RUN} tests/benchmarks/bench_Lgrid_2D_large.cpp
	# ${RUN} tests/benchmarks/distributions/make_distributions.cpp
	# python tests/benchmarks/distributions/make_distributions.py
	# nsmake run tests/benchmarks/bench_geogram_3D.cpp . 
