
all:
	# nsmake run -g3 tests/benchmarks/bench_ConvexPolyhedron2.cpp
	# nsmake run -g3 tests/test_ConvexPolyhedron2.cpp
	# nsmake run -g3 tests/benchmarks/bench_Zgrid_2D.cpp
	# nsmake run tests/benchmarks/bench_CGAL.cpp
	# nsmake run -g3 tests/test_RadixSort.cpp
	# nsmake run -I/usr/local/include/geogram1 -g3 tests/benchmarks/bench_geogram_delaunay.cpp
	# nsmake run -g3 tests/benchmarks/make_distrib_voro.cpp
	# nsmake run -g3 tests/test_IntrusivePool.cpp
	# nsmake run -g3 tests/test_PointerWithOffset.cpp
	# nsmake run -g3 tests/test_ConvexPolyhedron3.cpp
	# nsmake run tests/Grids/test_LGrid_2D.cpp
	nsmake run -g3 --exec-with valgrind tests/test_solve_2D.cpp
	# nsmake run -g3 tests/benchmarks/bench_Lgrid_2D.cpp
	# python tests/benchmarks/distributions/make_distributions.py
	# nsmake run tests/benchmarks/bench_geogram_3D.cpp . 
